### PR TITLE
Added 2 more laptop models to the laptop compatibility section

### PR DESCRIPTION
**Pull request by ronakchauhan97**
Added HP 240 G3 and Lenovo B41-80 to the list of compatible laptops

### CODE REVIEW

**Comment by JoshStrobl** [comment]
Please [squash your commits](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History), otherwise LGTM, thanks! :+1:

**Comment by ronakchauhan97** [comment]
I am not able to do squash the commits, getting error : - line 267: vi:
command not found.

Please merge these as they are, I will make sure to make all changes in 1
commit from next time onwards

**Comment by JoshStrobl** [comment]
Just sounds like its trying to use vi as the editor for git commit. Can always install vim or do something like `export EDITOR=nano`

I'm not merging unless it's squashed. It keeps the git history clean.

**Comment by JoshStrobl** [comment]
Now dup of #5 apparently. Closing to pull that in.

**Pull request closed without merging**
