### PR TITLE
Changed Zsh link

### PR DESCRIPTION
**Pull request by ICA3DaR5**
Changed the Zsh link to https://www.zsh.org/, according to [Wikipedia](https://en.wikipedia.org/wiki/Z_shell)

### CODE REVIEW

**Comment by JoshStrobl** [comment]
Except the ZSH URL is completely valid. If you went to the actual webpage you'd see "Zsh web pages" clearly goes to the sourceforge URL. Also you need to rebase, because I already merged in your previous changes. And start working on a different branch instead of master.

**Comment by ICA3DaR5** [comment]
Okay, sorry for that!

Thanks for your input.

**Comment by JoshStrobl** [comment]
It's alright, we're all new to git at some point :smile:

**Comment by ICA3DaR5** [comment]
I am not new to Git. I am new to GitHub :crying_cat_face:

**Pull request closed without merging**
