### PR TITLE
vlc is no longer shipped by defualt so reflect that in the help docs

### PR DESCRIPTION
**Pull request by fagoatse**

### CODE REVIEW

**Comment by JoshStrobl** [comment]
1. MPV isn't shipped by default yet. We haven't put out an ISO with that change.
2. The appropriate link for GNOME MPV is https://gnome-mpv.github.io/
3. These commits need to be squashed.

**Comment by fagoatse** [comment]
1. Right, I thought new spins were already out.
2. Thanks. Didn't find any links on their github project.
3. I'm not sure I can squash from within the web interface. If you can squash it for me please do so.

**Comment by JoshStrobl** [comment]
IIRC squashing on GitHub messes with the commit history. You'll need to clone your fork of help-center-docs and squash them locally then force push.

**Comment by fagoatse** [comment]
Well, give it a try anyway. If it's messed up i'll set up git and do it locally later.

**Comment by JoshStrobl** [comment]
> Well, give it a try anyway.

No, because then I'm just going to have to revert commits, further messing with the log. Squash the commits locally, thank you.

**Pull request merged**
