### PR TITLE
changes to reflect tweak tool preinstalled

### PR DESCRIPTION
**Pull request by lukewiwa**

### CODE REVIEW

**Comment by NeilWB** [comment]
I could be wrong but I believe the Tweak Tool was preinstalled by accident in the last Budgie ISO and won't be included by default going forwards (as shown [here](https://dev.solus-project.com/rIMGBe1c943d381c4d0639c66f2a1ff3d0de868208508).)

**Comment by lukewiwa** [comment]
Ah if that's the case then that's fair enough

**Comment by orschiro** [comment]
If tweak tool is not going to be installed by default anymore, then auto-starting applications on boot should be possible from the settings.

**Comment by JoshStrobl** [comment]
@orschiro Yes, it will be possible in the new Budgie Settings. Closing this as wontfix, I'll update the appropriate documentation to reflect functionality represented in Budgie Settings when we do the next Budgie release.

**Pull request closed without merging**
