### PR TITLE
Issue #22 Add verification section to Installation ISO (Linux and Mac) 

### PR DESCRIPTION
**Pull request by nadershamma**
I've added some instructions to validate the ISO to the "preparing-to-install" page. The instructions are for Linux and Mac users, I need to do some research for Windows, I am guessing stuff needs to be downloaded for that. 

It would be good if there was a way to validate the public key fingerprint to make sure that even the key is valid before checking the checksum signature and then the ISO but I am not sure how to achieve this, I am assuming the public key fingerprint needs to be securely available somewhere for people to reference?

### CODE REVIEW

**Comment by nadershamma** [comment]
On the topic of verifying the public key, I notices that openSUSE publish the fingerprint on the download page ([https://software.opensuse.org/distributions/tumbleweed](https://software.opensuse.org/distributions/tumbleweed)), can something similar be done with Solus?
 Then I can include the fingerprint command in the instructions and what to compare.

**Comment by JoshStrobl** [comment]
> can something similar be done with Solus?

We already provide a link to our public key in multiple locations.

**Comment by nadershamma** [comment]
Oh yes of course I know you provide the public key and it is brilliant that you do. That is not what I am meant. The public key is used to verify the files that verify the iso. What I meant was actually verifying the public key is the right key in the first place. I got the wrong end of the stick from openSUSE so ignore that sorry.

Looking at the GnuPG page: 

> ... you have a copy of our keys and the signatures are valid, but either you have not marked the keys as trusted or the keys are a forgery. In this case, at the very least, you should compare the fingerprints that are shown to those on the signing keys page. Even better is to compare the fingerprints with those shown on our business cards, which we handout at events that we attend. 

on this page [Signature Key](https://www.gnupg.org/signature_key.html) they provide the fingerprint of the public key for comparison. 

I might be getting the wrong end of the stick or going overboard but I am wondering if there is a way we can check that the public key provided, as you have correctly pointed out, is the legitimate key and not a forgery.

**Comment by JoshStrobl** [comment]
It's coming from our server, if it's forged then that means someone gained access and was able to change it, and at that point we have bigger issues than just that single file.

**Comment by nadershamma** [comment]
Well yes, and that's the point. If there was no risk of someone gaining access to your servers and files then you wouldn't need to sign and validate the ISO in the first place. Either way, it's just a suggestion, whether or not you choose to adopt it in the future is up to you really. 

More importantly I hope the addition of the Linux/Mac verification steps will suffice, I found that windows user can download an FOSS gpg suite called [gpg4win](https://www.gpg4win.org/), I can add a recommendation for windows user to go that site and follow their instructions on verifying the ISO from there. I can either do that later when I am not at work or make it as a separate pull request.

**Pull request merged**
