### PR TITLE
Packaging on Solus playlist

### PR DESCRIPTION
**Pull request by kyrios123**
I think it would be nice and helpful to add the Packaging playlist from the Solus youtube channel (especially since a few things are still missing on the help center at the moment like instructions for updating a package for example).

### CODE REVIEW

**Comment by JoshStrobl** [comment]
Rejected. The packaging videos are outdated (such as talking about evobuild instead of solbuild) and thus would only confuse the user. While the packaging videos were a good idea, not entirely sure it's viable for me to keep them updated.

**Comment by JoshStrobl** [comment]
Note: I will add information on updating packages.

**Comment by kyrios123** [comment]
No problem, I understand.
Although the videos are outdate (evobuild, ...) I found them helpful as a complement of the info currently published on the help center. But you're right, it might be confusing.

You do a really great job, Josh... I am impressed by all the things you do, it's really amazing ! :)

**Comment by JoshStrobl** [comment]
> I found them helpful as a complement of the info currently published on the help center.

Totally understandable and I'm sorry that they're outdated in the first place. We just evolve things at a pace that doesn't make it sustainable to maintain them. For example, a multitude of macros have been added since the release of the v2 videos, so the Keys, Macros, and Variables video is already outdated too.

I have some ideas brewing though, like more regular streams where I walk people through packaging.

**Comment by JoshStrobl** [comment]
One last update :smile: Having a second Learn Solus Packaging livestream session on Saturday, March 4th at 1800 GMT: https://www.youtube.com/watch?v=oMMfc8XxZhc

**Pull request closed without merging**
